runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyClbFOzWkT3-HzDmC4q9c-DeE8bhSEHJWE

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/.*
  - url: /(.*\.js)
    redirect_http_response_code: 301
    static_files: dist/\1
    upload: dist/.*\.js
  - url: /(.*\.css)
    redirect_http_response_code: 301
    static_files: dist/\1
    mime_type: text/css
    upload: dist/.*\.css
  - url: /(.*\.(.+))$
    static_files: dist/\1
    upload: dist/(.*\.(.+))$
  - url: /.*
    static_files: dist/index.html
    upload: dist/.*

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
